"""add education and work experience to profile

Revision ID: 2ed86509173b
Revises: 
Create Date: 2025-04-30 12:34:05.764924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ed86509173b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('education', sa.JSON(), nullable=True))
    op.add_column('profiles', sa.Column('work_experience', sa.JSON(), nullable=True))
    op.drop_column('profiles', 'experience')
    op.drop_column('profiles', 'job_title')
    op.drop_column('profiles', 'company')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('company', sa.VARCHAR(), nullable=True))
    op.add_column('profiles', sa.Column('job_title', sa.VARCHAR(), nullable=True))
    op.add_column('profiles', sa.Column('experience', sa.VARCHAR(), nullable=True))
    op.drop_column('profiles', 'work_experience')
    op.drop_column('profiles', 'education')
    # ### end Alembic commands ###
